id: A86667DD2
title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration for
  the Flourishing and Spread of the Ancient Translation Tradition'
type: translation
pechas:
- IF4994C91
- IA5488A07
- I6499C69A
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:05:09.368364
  last_modified_at: 2023-01-04 13:05:09.368375
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF4994C91/D0F8: '5116'
  IA5488A07/5555: '5116'
  I6499C69A/8CB5: '5116'
